spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/finance_tracker
    user: postuser
    password: passuser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
liquibase:
  changelog:
    path: db/changelog/changelog.xml
application:
  description: Finance tracker application
  version: 4