spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/finance_tracker
    user: postuser
    password: passuser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate